name: Create Release

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'  
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Vue.js App
      run: npm run build

    - name: Install pkg
      run: npm install pkg

    - name: Create Binary File
      run: npm run pkg

    - name: Archive production artifacts
      run: |
        mkdir -p release
        zip -r release/release.zip dist/
      shell: bash

    - name: Verify release artifact
      run: ls -la release/

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Changes in this release:
          - List your changes here
        draft: false
        prerelease: false

    - name: Upload release assets (dist)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/release.zip
        asset_name: release.zip
        asset_content_type: application/zip

    - name: Upload release assets (binary)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/my-vue-app-linux
        asset_name: binaryfile.bin
        asset_content_type: application/octet-stream

    # - name: Upload Release Assets
    #   id: upload-assets
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: |
    #       myapp.zip
    #       dist/my-vue-app-linux
    #     asset_name: |
    #       myapp.zip
    #       my-vue-app-linux
    #     asset_content_type: |
    #       application/zip
    #       application/octet-stream
    #     github_token: ${{ secrets.GITHUB_TOKEN }}