name: Create Release

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'  
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Vue.js App
      run: npm run build

    - name: Create Binary File
      run: |
        # Replace this command with your actual command to generate the binary file
        echo "This is a placeholder for generating the binary file" > binaryfile.exe

    - name: Zip App
      run: |
        zip -r myapp.zip dist/*

    - name: Upload Release Assets
      id: upload-assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: |
          myapp.zip
          binaryfile.exe
        asset_name: |
          myapp.zip
          binaryfile.exe
        asset_content_type: |
          application/zip
          application/octet-stream
        github_token: ${{ secrets.GITHUB_TOKEN }}