name: Create Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS Environment ${{ matrix.node-versions }}
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run build
    - run: zip -r  ./electron-${{ github.run_number }}.zip ./dist/electron/*

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: Automated Electron Deployment
        draft: false
        prerelease: false

    - name: Upload a Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./electron-${{ github.run_number }}.zip
        asset_name: electron-${{ github.run_number }}.zip
        asset_content_type: appliction/zip