name: Create Release

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'  
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: npm run build --production --release --static --no-debug --link-flags="-s -Wl,-z,relro,-z,now"
    - name: Upload
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/oq
        asset_name: oq-${{ github.event.release.tag_name }}-linux-x86_64
        asset_content_type: binary/octet-stream