name: Create Release

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'  
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Vue.js App
      run: npm run build

    - name: List Contents of dist Directory
      run: ls -R dist

    - name: Create Binary File
      run: |
        # Ensure this path matches your actual bundle location
        mv dist/js/app.js binaryfile.js
      shell: bash

    - name: Zip App
      run: |
        zip -r myapp.zip dist
      shell: bash

    - name: List Contents for Debugging
      run: ls -R
      shell: bash

    - name: Get current date and time
      id: datetime
      run: echo "RELEASE_TAG=release-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        body: |
          Release notes for ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload-assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          myapp.zip
          binaryfile.js
        asset_name: |
          myapp.zip
          binaryfile.js
        asset_content_type: |
          application/zip
          application/javascript
        github_token: ${{ secrets.GITHUB_TOKEN }}